version: '3.7'
services:
 python:
   build: .
   tty: true
   image: python
   container_name: flask
   volumes:
     - ./:/usr/src/app
   ports:
     - 5000:5000
   command: flask run --host 0.0.0.0 --port 5000
   environment:
     - FLASK_APP=web.py
     - CELERY_BROKER=redis://redis
     - CELERY_BACKEND=redis://redis
   depends_on:
     - redis

 celery:
   image: python
   tty: true
   container_name: celery
   volumes:
     - ./:/usr/src/app
   command: celery -A celery_tasks worker --loglevel=info --logfile=logs/celery.log
   environment:
     # `COLUMNS` is needed for Python 3.8: https://github.com/celery/celery/issues/5761
     - COLUMNS=80
     - CELERY_BROKER=redis://redis
     - CELERY_BACKEND=redis://redis
   depends_on:
     - python
     - redis

 redis:
   image: redis:5.0.7-buster
   container_name: redis
   tty: true

 monitor:
   image: python
   tty: true
   container_name: monitor
   ports:
     - 5555:5555
   command: flower -A celery_tasks --port=5555 --broker=redis://redis
   depends_on:
     - python
     - redis
